# Generated by Django 3.2.20 on 2023-08-30 22:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dokonlar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=' ', max_length=150)),
                ('location', models.CharField(default=' ', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Oziq_ovqat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='osh', max_length=130)),
                ('type', models.CharField(default=' ', max_length=50)),
                ('surogi', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
    ]
